# Generated by Django 4.1.7 on 2023-03-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Posts_Imagies/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
